# EDA: hospedagem e criminalidade em Rio de Janeiro

Análise exploratória conjunta dos datasets de Airbnb e crimes.

In [2]:
from pathlib import Path
import geopandas as gpd
import pandas as pd

PROJECT_ROOT = next(
    path for path in (Path.cwd(), *Path.cwd().parents)
    if (path / "data").is_dir()
)
DATA_DIR = PROJECT_ROOT / "data"

In [3]:
listings = pd.read_csv("../../data/listings.csv")
listings

C:\Users\rafamega\AppData\Local\Temp\ipykernel_20652\3338355115.py:1: DtypeWarning: Columns (0: host_profile_url, 1: price, 2: price_quote_checkin_date, 3: price_quote_checkout_date, 4: price_quote_raw, 5: neighborhood_overview, 6: host_since, 7: host_response_time, 8: host_response_rate, 9: host_acceptance_rate, 10: host_thumbnail_url, 11: host_neighbourhood, 12: host_verifications, 13: neighbourhood, 14: instant_bookable) have mixed types. Specify dtype option on import or set low_memory=False.
  listings = pd.read_csv("../../data/listings.csv")

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_thumbnail_url,host_neighbourhood,host_total_listings_count,host_verifications,neighbourhood,instant_bookable
0,1025196153924029661,https://www.airbnb.com/rooms/1025196153924029661,20260624212719,2026-06-25,city scrape,Quartos disponíveis no Recreio,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,546603190,https://www.airbnb.com/users/show/546603190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1697400829368754530,https://www.airbnb.com/rooms/1697400829368754530,20260624212719,2026-06-25,city scrape,Casa próxima a Floresta da Tijuca,Take a break to relax in this serene oasis in ...,https://a0.muscache.com/pictures/hosting/Hosti...,737983482,https://www.airbnb.com/users/show/737983482,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,42874066,https://www.airbnb.com/rooms/42874066,20260624212719,2026-06-25,city scrape,Alugo uma vaga para sexo feminino Recreio,NaN,https://a0.muscache.com/pictures/43e779d6-58df...,341395950,https://www.airbnb.com/users/show/341395950,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1543530193994981165,https://www.airbnb.com/rooms/1543530193994981165,20260624212719,2026-06-26,previous scrape,Barra Vista maravilhosa,"Kick back and relax in this calm, stylish space.",https://a0.muscache.com/pictures/hosting/Hosti...,173836079,https://www.airbnb.com/users/show/173836079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,831750365913119274,https://www.airbnb.com/rooms/831750365913119274,20260624212719,2026-06-25,city scrape,Suíte Rio BR,Spacious and pleasant suite in a family home.,https://a0.muscache.com/pictures/miso/Hosting-...,69238992,https://www.airbnb.com/users/show/69238992,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179632,1651790928149305935,https://www.airbnb.com/rooms/1651790928149305935,20260330062336,2026-04-02,city scrape,Av. Atlântica | Vista Mar Incrível | Suíte Premi,"Comfortable sea-facing suite in Copacabana, on...",https://a0.muscache.com/pictures/hosting/Hosti...,357078569,https://www.airbnb.com/users/show/357078569,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179633,1652082025241101165,https://www.airbnb.com/rooms/1652082025241101165,20260330062336,2026-04-02,city scrape,Copacabana: Praia e Conforto | 5 Hóspedes,NaN,https://a0.muscache.com/pictures/prohost-api/H...,12335830,https://www.airbnb.com/users/show/12335830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179634,1652148096386184589,https://www.airbnb.com/rooms/1652148096386184589,20260330062336,2026-04-02,city scrape,Amplo e bem localizado Apê em Copacabana,"Spacious apartment in Copacabana, just minutes...",https://a0.muscache.com/pictures/hosting/Hosti...,513633037,https://www.airbnb.com/users/show/513633037,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179635,1652264749683808805,https://www.airbnb.com/rooms/1652264749683808805,20260330062336,2026-04-02,city scrape,Apartamento para trabalho e para casal,Keep it simple at this peaceful and centrally-...,https://a0.muscache.com/pictures/hosting/Hosti...,754155809,https://www.airbnb.com/users/show/754155809,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179636,1652323674070723839,https://www.airbnb.com/rooms/1652323674070723839,20260330062336,2026-04-02,city scrape,Casa AME,"Casa AME is located near Maracanã Stadium, res...",https://a0.muscache.com/pictures/hosting/Hosti...,436313572,https://www.airbnb.com/users/show/436313572,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
crimes = pd.read_csv("../../data/crime_data/BaseDPEvolucaoMensalCisp.csv", encoding="latin-1", sep=";")
crimes

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38131,159,7,2026,2026m07,11,7,Cachoeiras de Macacu,3300803,Interior,0,...,3.0,0.0,21,3,0,0,0,0,148,2
38132,165,7,2026,2026m07,33,5,Mangaratiba,3302601,Interior,2,...,8.0,0.0,40,1,0,0,0,0,180,2
38133,166,7,2026,2026m07,33,5,Angra dos Reis,3300100,Interior,3,...,21.0,3.0,96,4,0,0,0,0,710,2
38134,167,7,2026,2026m07,43,5,Paraty,3303807,Capital,1,...,3.0,0.0,27,2,1,0,0,0,206,2
38135,168,7,2026,2026m07,28,5,Rio Claro,3304409,Interior,0,...,0.0,0.0,4,2,0,0,0,0,52,2

In [5]:
cisp = gpd.read_file(
    "../../data/shape_file/CISPshp/CISPshp/cisp.shp"
)

aisp = gpd.read_file(
    "../../data/shape_file/AISPshp/SHP/aisp.shp"
)

risp = gpd.read_file(
    "../../data/shape_file/RISPshp/RISPshp/risp.shp"
)

# Merge Datasets

In [ ]:
# Crimes - mes a mes - cisp, aisp, risp
# bookings - trimestral - coordenadas
# shape files - cisp, aisp, risp